version: '3.8'

networks:
  app-network:

volumes:
  app-data:


services:

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
        - "8080:8080"
    networks:
        app-network:

  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:

  db:
    image: mysql:8.0
    container_name: db
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
        - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
        - ./.docker/mysql_data/mysql:/var/lib/mysql
    networks:
       app-network:
    depends_on:
        - backend
